### ISSUE TITLE
ookla License in Debian

### ISSUE THREAD

**Issue by luismiparra** [Derek-K/telegraf-speedtest#1]
At debian buster telegraf run by default using telegraf user.

To get the license accepted I follow this steps:

1. Run speed test as root (this create a license here /root/.config/ookla/speedtest-cli.json
2. mkdir /etc/telegraf/.config/; mkdir /etc/telegraf/.config/ookla      #this create folder at home for telegra
3. cp /root/.config/ookla/speedtest-cli.json /etc/telegraf/.config/ookla/speedtest-cli.json  # Copy the license to telegra user

**Comment by JackoAC** [comment]
Hello, i've recently started using telegraf, and i can't make it work, i've followed the instructions but i dont receive any information on my dashboard and i don't have any error that show up when i play the command.
Can someone help me find out ?

Thank in advance !
