### ISSUE TITLE
Accept the license as the telegraf user

### ISSUE THREAD

**Issue by jbuck2005** [Derek-K/telegraf-speedtest#7]
You must be sure to accept the Speedtest license as the telegraf user.
There is a catch however; you may need to change the permissions of /etc/telegraf for a moment.
When you run the subsequent speedtest command as the telegraf user, the following directory structure will be created:

/etc/telegraf
  ->.config
  ->->oolka
  ->->->speedtest-cli.json

Do so via:
````
sudo chmod 777 /etc/telegraf
sudo -u telegraf /usr/bin/speedtest
sudo chmod 755 /etc/telegraf
````

**Comment by jbuck2005** [comment]
Closing to retain documentation for others to see.

**Comment by Derek-K** [comment]
See #1

**Comment by jbuck2005** [comment]
So, because this is a known consideration .. and one should never have to read an issues queue to get something working, might I suggest you put this in the documentation (ie. README.MD) ?

Perhaps even make a script for people to use to do precisely what I've written above?

**Comment by NelsonMinar** [comment]
FWIW this error tripped me up. The speedtest client does print a useful error message to clue you in, but it'd be nice to avoid it.

```[error] Failed to save settings: boost::filesystem::create_directories: Permission denied: "/etc/telegraf/.config"
[error] Path used: /etc/telegraf/.config/ookla/speedtest-cli.json```
