### ISSUE TITLE
No metrics written

### ISSUE THREAD

**Issue by lee-costa** [Derek-K/telegraf-speedtest#8]
I am using this on Ubuntu to gather metrics and while following the steps provided, I am not receiving any data. I see this in the logs:

    Error in plugin: exec: exit status 1 for command ' sudo /usr/bin/speedtest -f json-pretty'

Any ideas?

**Comment by risb0r** [comment]
Likely the license roadblock.
Run `/usr/bin/speedtest -f json-pretty --accept-license --accept-gdpr`  for testing purposes and see how you go.

**Comment by lee-costa** [comment]
Ended up following instructions on this [this](https://github.com/Derek-K/telegraf-speedtest/issues/1) issue and it is now solved.

edit - Thank you.
